#%RAML 1.0
title: RestApiRamlDemo

/customers:
  get:
    queryParameters:
      requester:
        required: true
        type: string
        example: "Jhon"
      accountType:
        required: false
        type: /AccountTypeValues.raml