#%RAML 1.0
title: RestApiRamlDemo

types:
  Account: !include DataTypes/Account.raml
  AccountCreatePayload: !include DataTypes/AccountNoID.raml
  AccountTypeEnum: !include DataTypes/AccountTypeValues.raml

/customers:
  get:
    queryParameters:
      requester:
        required: true
        type: string
        example: "Jhon"
      accountType:
        required: false
        type: AccountTypeEnum
      customerName:
        required: false
        type: string
    responses:
      200:
        body:
          application/json:
            type: Account[]
            examples:
              output: !include /Examples/AccountCollection.raml
  post:
    body:
      application/json:
        type: AccountCreatePayload
        examples:
          input: !include /Examples/NewAccount.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Accounts created
