#%RAML 1.0 NamedExample
value:
  -
    ID: 1
    Name: Jhon
    Type: personal
    Address: 12345 Green St,Boulder,Colorado,82433,USA
    AirMiles: 32
    CreationDate: Sun, 28 Feb 2016 17:41:41 GMT
  -
    ID: 2
    Name: Jane
    Type: business
    Address: 12346 Green St,Boulder,Colorado,82433,USA
    AirMiles: 12
    CreationDate: Sun, 28 Feb 2017 16:41:41 GMT