#%RAML 1.0 NamedExample
value:
  -
    ID: 1
    Name: Jhon
    Type: personal
    Address: 12345 Green St,Boulder,Colorado,82433,USA
    AirMiles: 32
    CreationDate: 2017/07/26 17:29
  -
    ID: 2
    Name: Jane
    Type: business
    Address: 12346 Green St,Boulder,Colorado,82433,USA
    AirMiles: 12
    CreationDate: 2017/07/27 16:29    